import type { Event } from '@/lib/types';
import EventCard from './EventCard';
import { PlaceHolderImages } from '@/lib/placeholder-images';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'AI & The Future of Work',
    date: 'September 15, 2025',
    location: 'Virtual',
    description: 'Explore how artificial intelligence is reshaping industries and careers in this groundbreaking virtual summit. Join leaders from around the world.',
    tags: ['AI', 'Technology', 'Future'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-1')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-1')?.imageHint || '',
    price: 1,
  },
  {
    id: '2',
    title: 'Global Hackathon 2025',
    date: 'September 20-22, 2025',
    location: 'San Francisco, CA',
    description: 'The world\'s largest hackathon returns. Build, learn, and compete with the brightest minds for amazing prizes. Innovation starts here.',
    tags: ['Hackathon', 'Coding', 'Innovation'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-2')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-2')?.imageHint || '',
    price: 0,
  },
  {
    id: '3',
    title: 'Creative Design Summit',
    date: 'October 5, 2025',
    location: 'Virtual',
    description: 'A full day of inspiring talks and hands-on workshops from the leading minds in the design industry. Perfect for UX/UI and graphic designers.',
    tags: ['Design', 'UX/UI', 'Creative'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-3')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-3')?.imageHint || '',
    price: 1,
  },
    {
    id: '4',
    title: 'Web3 Forward Conference',
    date: 'October 18-19, 2025',
    location: 'Miami, FL',
    description: 'A two-day deep dive into the decentralized future. Connect with blockchain experts, developers, and pioneers shaping the next wave of the internet.',
    tags: ['Web3', 'Blockchain', 'Crypto'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-4')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-4')?.imageHint || '',
    price: 1,
  },
  {
    id: '5',
    title: 'Data Science & Machine Learning Expo',
    date: 'November 1-3, 2025',
    location: 'New York, NY',
    description: 'Discover the latest trends and applications in data science and machine learning. Network with industry professionals and academics.',
    tags: ['Data Science', 'ML', 'Analytics'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-5')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-5')?.imageHint || '',
    price: 1,
  },
  {
    id: '6',
    title: 'Startup Pitch Night',
    date: 'November 15, 2025',
    location: 'Austin, TX',
    description: 'Watch the most promising startups pitch their ideas to a panel of venture capitalists. Your chance to see the next big thing.',
    tags: ['Startups', 'Venture Capital', 'Pitch'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-6')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-6')?.imageHint || '',
    price: 0,
  },
  {
    id: '7',
    title: 'GreenTech Innovation Forum',
    date: 'December 1, 2025',
    location: 'Virtual',
    description: 'Join sustainability leaders and innovators to discuss how technology can solve the world\'s most pressing environmental challenges.',
    tags: ['GreenTech', 'Sustainability', 'Climate'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-7')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-7')?.imageHint || '',
    price: 0,
  },
  {
    id: '8',
    title: 'Mobile Developers Conference',
    date: 'December 8-9, 2025',
    location: 'Berlin, Germany',
    description: 'The premier event for mobile developers. Learn about the latest in iOS, Android, and cross-platform development.',
    tags: ['Mobile', 'iOS', 'Android'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-8')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-8')?.imageHint || '',
    price: 1,
  },
  {
    id: '9',
    title: 'Cloud Native Summit',
    date: 'December 15, 2025',
    location: 'Seattle, WA',
    description: 'Dive into the world of cloud-native technologies, from Kubernetes to serverless. A must-attend for DevOps and backend engineers.',
    tags: ['Cloud', 'DevOps', 'Kubernetes'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-9')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-9')?.imageHint || '',
    price: 1,
  },
  {
    id: '10',
    title: 'FinTech Revolution',
    date: 'January 10-11, 2026',
    location: 'London, UK',
    description: 'Explore the intersection of finance and technology. Topics include digital banking, payment gateways, and DeFi.',
    tags: ['FinTech', 'Finance', 'Blockchain'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-10')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-10')?.imageHint || '',
    price: 1,
  },
  {
    id: '11',
    title: 'HealthTech Forward',
    date: 'January 20, 2026',
    location: 'Virtual',
    description: 'Discover how technology is transforming healthcare, from telemedicine to AI-powered diagnostics.',
    tags: ['HealthTech', 'Healthcare', 'AI'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-11')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-11')?.imageHint || '',
    price: 0,
  },
  {
    id: '12',
    title: 'E-commerce Expo',
    date: 'January 28, 2026',
    location: 'Chicago, IL',
    description: 'The premier event for online retailers. Learn about the latest trends in e-commerce, marketing, and logistics.',
    tags: ['E-commerce', 'Marketing', 'Retail'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-12')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-12')?.imageHint || '',
    price: 1,
  },
  {
    id: '13',
    title: 'Gaming Universe',
    date: 'February 1-3, 2026',
    location: 'Los Angeles, CA',
    description: 'A three-day celebration of gaming. Get hands-on with upcoming titles and meet your favorite developers.',
    tags: ['Gaming', 'Esports', 'Entertainment'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-13')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-13')?.imageHint || '',
    price: 1,
  },
  {
    id: '14',
    title: 'Cybersecurity Conclave',
    date: 'February 15, 2026',
    location: 'Virtual',
    description: 'Join top cybersecurity experts to discuss the latest threats and defense strategies in the digital world.',
    tags: ['Cybersecurity', 'Security', 'Privacy'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-14')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-14')?.imageHint || '',
    price: 0,
  },
  {
    id: '15',
    title: 'Future of Transportation',
    date: 'February 25, 2026',
    location: 'Detroit, MI',
    description: 'From autonomous vehicles to electric aviation, explore the future of how we move.',
    tags: ['Mobility', 'Automotive', 'Technology'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-15')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-15')?.imageHint || '',
    price: 1,
  },
  {
    id: '16',
    title: 'EdTech Summit 2026',
    date: 'March 1, 2026',
    location: 'Virtual',
    description: 'Explore how technology is revolutionizing education, from K-12 to lifelong learning.',
    tags: ['EdTech', 'Education', 'AI'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-16')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-16')?.imageHint || '',
    price: 0,
  },
  {
    id: '17',
    title: 'Space Exploration Symposium',
    date: 'March 10, 2026',
    location: 'Houston, TX',
    description: 'Join astronauts, engineers, and scientists to discuss the future of space exploration and colonization.',
    tags: ['Space', 'Science', 'Exploration'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-17')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-17')?.imageHint || '',
    price: 1,
  },
  {
    id: '18',
    title: 'Robotics & Automation Fair',
    date: 'March 15-16, 2026',
    location: 'Tokyo, Japan',
    description: 'See the latest in robotics and automation from leading companies and research institutions.',
    tags: ['Robotics', 'Automation', 'AI'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-18')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-18')?.imageHint || '',
    price: 1,
  },
  {
    id: '19',
    title: 'Virtual Reality World',
    date: 'March 22, 2026',
    location: 'Virtual',
    description: 'Immerse yourself in the world of VR and AR. Experience the latest hardware and software innovations.',
    tags: ['VR', 'AR', 'Metaverse'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-19')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-19')?.imageHint || '',
    price: 0,
  },
  {
    id: '20',
    title: 'AgriTech Conference',
    date: 'March 28, 2026',
    location: 'Des Moines, IA',
    description: 'Learn how technology is shaping the future of agriculture, from precision farming to sustainable practices.',
    tags: ['AgriTech', 'Farming', 'Sustainability'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-20')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-20')?.imageHint || '',
    price: 1,
  },
  {
    id: '21',
    title: 'Quantum Computing Summit',
    date: 'September 5-6, 2025',
    location: 'Zurich, Switzerland',
    description: 'A deep dive into the world of quantum computing. Connect with leading researchers and innovators.',
    tags: ['Quantum', 'Computing', 'Science'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-21')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-21')?.imageHint || '',
    price: 1,
  },
  {
    id: '22',
    title: 'The Creator Economy',
    date: 'September 12, 2025',
    location: 'Virtual',
    description: 'Learn how to build a career as a content creator. Topics include monetization, audience growth, and branding.',
    tags: ['Creators', 'Social Media', 'Marketing'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-22')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-22')?.imageHint || '',
    price: 0,
  },
  {
    id: '23',
    title: 'Smart Cities Expo',
    date: 'September 25, 2025',
    location: 'Singapore',
    description: 'Explore the technologies and strategies that are making our cities smarter, more sustainable, and more livable.',
    tags: ['Smart City', 'IoT', 'Urban'],
    imageUrl: PlaceHolderImages.find(p => p.id === 'event-23')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'event-23')?.imageHint || '',
    price: 1,
  },
];

export default function FeaturedEvents() {
  return (
    <section id="events" className="py-12 md:py-20">
      <div className="text-center mb-10">
        <h2 className="font-headline text-3xl md:text-4xl font-bold">Featured Events</h2>
        <p className="text-muted-foreground mt-2">Join thousands of innovators at our upcoming events.</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {MOCK_EVENTS.map((event) => (
          <EventCard key={event.id} event={event} />
        ))}
      </div>
    </section>
  );
}
